sudo: required
services:
  - docker
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
cache:
  directories:
  - $HOME/google-cloud-sdk
before_install:
  - docker build -t imparaai/go-figure-web .
  - docker run -d --name web imparaai/go-figure-web
script:
  - docker exec web bash -c "/var/www/go-figure/node_modules/@angular/cli/bin/ng test --watch=false"
  - docker exec web bash -c "/var/www/go-figure/node_modules/@angular/cli/bin/ng e2e --port 4202"
deploy:
  provider: script
  script: bash deploy
  on:
    branch: master
notifications:
  email:
    on_success: never