sudo: required
services:
  - docker
before_install:
  - docker build -t imparaai/go-figure-web .
  - docker run -d --name web imparaai/go-figure-web
script:
  - docker exec web "ng test --watch=false"
  - docker exec web "ng e2e --port 4202"
notifications:
  email:
    on_success: never