sudo: required
services:
  - docker
before_install:
  - docker build -t imparaai/go-figure-web .
  - docker run -d --name web imparaai/go-figure-web
script:
  - docker exec web bash -c "/var/www/go-figure/node_modules/@angular/cli/bin/ng test --watch=false"
  - docker exec web bash -c "/var/www/go-figure/node_modules/@angular/cli/bin/ng e2e --port 4202"
deploy:
  provider: script
  script: bash dockerhub_push
  on:
    branch: master
notifications:
  email:
    on_success: never