sudo: required
services:
  - docker
env:
  global:
  - CLOUDSDK_CORE_DISABLE_PROMPTS=1
cache:
  directories:
  - $HOME/google-cloud-sdk
before_script:
  - docker build --target builder -t imparaai/go-figure-web:dev .
  - docker build -t imparaai/go-figure-web .
  - docker run -d --name web imparaai/go-figure-web:dev
script:
  - docker exec web /bin/sh -c "ng test --watch=false"
  - docker exec web /bin/sh -c "ng e2e --port 4202"
deploy:
  provider: script
  script: bash deploy
  on:
    branch: master
notifications:
  email:
    on_success: never