#!/bin/bash
echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin
docker push imparaai/go-figure-web
docker push imparaai/go-figure-web:dev

openssl aes-256-cbc -K $encrypted_12c8071d2874_key -iv $encrypted_12c8071d2874_iv -in gce-deploy-service-account.json.enc -out gce-deploy-service-account.json -d

if [ ! -d $HOME/google-cloud-sdk/bin ]; then
  rm -rf $HOME/google-cloud-sdk;
  curl https://sdk.cloud.google.com | bash > /dev/null;
fi

source $HOME/google-cloud-sdk/path.bash.inc
gcloud components update kubectl
gcloud auth activate-service-account --key-file gce-deploy-service-account.json

gcloud container clusters get-credentials go-figure --zone us-central1-a --project imparaai-sergio
kubectl patch deployment web -p "{\"spec\":{\"template\":{\"metadata\":{\"labels\":{\"date\":\"`date +'%s'`\"}}}}}"